### ISSUE TITLE
How to order collections in the left menu

### ISSUE THREAD

**Issue by digitalfredy** [sighingnow/jekyll-gitbook#123]
Hello,

Following #100 where the collections usage was proposed I was capable to group parts of my document and it is great but now I have a problem, I can no put those collections in the right order.

Think I have those collections:

- Start
- End

Unfortunately the left menu do his index in alphabetical order then it shows first all the content related with the *End* and then all the content related with the *Start* which is not great for a book

I guess the easiest way (as user) is to use the same order they are written in the `_config.yml` file

**Comment by digitalfredy** [comment]
Another option is to use `weight`

```
collections:
  Start:
    output: true
    permalink: /:collection/:path/
    weight: 10
  End:
    output: true
    permalink: /:collection/:path/
    weight: 20
```

Note `weight` is already used for posts as described [here](https://stackoverflow.com/questions/37277738/can-i-create-nested-collections-in-jekyll/50763242#50763242)

**Comment by sighingnow** [comment]
> I guess the easiest way (as user) is to use the same order they are written in the _config.yml file

I agree with this proposal. Will implement it ASAP.

**Comment by zhaozewang** [comment]
One simple workaround is to name your collections in alphabetical order and then change their names in the permalinks so that they are almost transparent to the users.

For example, suppose I have two collections, "apple" and "banana," and I want the "banana" to appear before "apple" in toc. In the `_config.yml', I could just write:

```yaml
collections:
  collection_1:
    output: true
    permalink: /banana/:path/
  collection_2:
    output: true
    permalink: /apple/:path/
```
